version: '3'
networks:
  pdc-net: # Docker-only overlay network
    ipam:
      config:
        - subnet: 172.23.0.0/16
  # bridge-net: # Only needed if need to talk to external network
  #   driver: bridge
  #   ipam:
  #     config:
  #       - subnet: 172.24.0.0/16

services:
  serverrouter:
    build: .
    command: ["TCPServerRouter"]
    networks:
      pdc-net:
        ipv4_address: 172.23.0.5
      # bridge-net: # external network bridge, makes ports available on host
      #   ipv4_address: 172.24.0.5
    ports:
      - "5555:5555"
      - "5555:5555/udp"
  server:
    build: .
    command: ["TCPServer"]
    depends_on:
      - serverrouter
    networks:
      pdc-net:
        ipv4_address: 172.23.0.6

  client:
    build: .
    command: ["TCPClient", "song.mp3"]
    depends_on:
      - serverrouter
      - server
    networks:
      pdc-net:
        ipv4_address: 172.23.0.7
